"""
gosdt: Implementation of General Optimal Sparse Decision Tree and Fast Sparse Decision Tree Optimization via Reference Ensembles.
"""


from __future__ import annotations

# This file is generated by scikit-build-core
from ._version import version as __version__

from ._binarizer import NumericBinarizer
from ._threshold_guessing import ThresholdGuessBinarizer
from ._classifier import GOSDTClassifier
from ._libgosdt import Status

__all__ = ["__version__", "NumericBinarizer", "ThresholdGuessBinarizer", "GOSDTClassifier", "Status"]
